name: digitalgov
config:
  via: 'nginx:1.25'
services:
  cache:
    type: 'memcached:1.5.12'
  node:
    type: 'node:24'
    build:
      - ./orch/build_node.sh
    scanner: false
    globals:
      gulp-cli: latest
  appserver_nginx:
    build_as_root:
      # See https://github.com/lando/drupal/issues/124
      - sed 's|daemon|www-data|g' -i /opt/bitnami/scripts/nginx-env.sh
tooling:
  be:
    service: appserver
    cmd: "env COMPOSER_DEV=1 ./orch/build.sh"
  fe:
    service: node
    cmd: "./orch/build_node.sh"

