adding:
  sp_entity_id: ''
  sp_name_id_format: ''
  sp_x509_certificate: ''
  sp_new_certificate: ''
  sp_private_key: ''
  metadata_valid_secs: 1
  idp_entity_id: STAGE-ENTITY-ID
  idp_single_sign_on_service: ''
  idp_single_log_out_service: ''
  idp_certs: {  }
  idp_cert_encryption: ''
  request_set_name_id_policy: true
  security_metadata_sign: false
  security_nameid_encrypt: false
  security_signature_algorithm: ''
  security_encryption_algorithm: ''
  security_assertions_signed: false
  security_assertions_encrypt: false
  security_nameid_encrypted: false
  security_want_name_id: true
  security_logout_reuse_sigs: false
  security_allow_repeat_attribute_name: false
  debug_display_error_details: false
  debug_log_in: false
  debug_log_saml_in: false
  debug_log_saml_out: false
  debug_phpsaml: false
  use_proxy_headers: false
removing:
  metadata_valid_secs: 60
