name: Validation

on:
  # Commit message validation requires a target branch which is only available in a PR.
  pull_request:
  push:
    branches:
      - 'feature/**'
    # This branch runs the 'build-and-deploy' action which also validates, no
    # need to validate here.
    branches-ignore:
      - 'feature/DIGITAL-*-deploydev'

jobs:
  validate:
    uses: ./.github/workflows/validation-run.yml
    secrets: inherit
