name: Validation

on:
  # Commit message validation requires a target branch which is only available in a PR.
  pull_request:
  push:
    branches:
      - 'feature/**'

jobs:
  validate:
    uses: ./.github/workflows/validation-run.yml
    secrets: inherit
